name: 'etl_test'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    etl_test:
        dbt-sandbox-373717:
            # Applies to all files under models/dbt-sandbox-373717/
            telemetry_derived:
                materialized: incremental
                +schema: telemetry_derived
            telemetry:
                materialized: view
                +schema: telemetry
            focus_android_derived:
                materialized: incremental
                +schema: focus_android_derived
            focus_android:
                materialized: view
                +schema: focus_android
            focus_ios_derived:
                materialized: incremental
                +schema: focus_ios_derived
            focus_ios:
                materialized: view
                +schema: focus_ios
            monitoring_derived:
                materialized: incremental
                +schema: monitoring_derived

    # ascholtz-dev:
    #     test_derived:
    #         materialized: table
    #         +schema: test_derived
    #     test:
    #         materialized: view
    #         +schema: test

