
version: 2

models:
    - name: focus_android_derived__metrics_clients_daily_v1
      description: "Daily per-client aggregates on top of metrics pings"
    - name: focus_android_derived__metrics_clients_last_seen_v1
      description: Window over the previous 28 days of the clients metrics daily table

